### ISSUE TITLE
Complains about lacking application

### ISSUE THREAD

**Issue by ccirello** [sourcegraph/sourcegraph-vscode#2]
Whenever I install it doesn't work, the error message is:
```
Failed to reach the Sourcegraph desktop application. Make sure it is running on your computer. Visit https://github.com/sourcegraph/sourcegraph-desktop for more information
```

And  https://github.com/sourcegraph/sourcegraph-desktop returns 404

**Comment by uforic** [comment]
Hey @ccirello , stay tuned - we are putting the finishing touches on Sourcegraph Desktop and Sourcegraph for VSCode, and we'd love to have you try it out on VSCode. Mind signing up on our [beta page](https://sourcegraph.com/beta)? 

This project got made public a bit too early, apologies for the false start. Closing this for now!

**Comment by ccirello** [comment]
@uforic done.

**Comment by emidoots** [comment]
LGTM.

You'll need to follow steps i. - viii. in https://github.com/sourcegraph/sourcegraph-vscode#development to release a new update in order for the README that vscode actually shows to users to update AFAIK (which is most important for this change).
